
export enum DocumentType {
  PDF = "PDF",
  WORD = "Word",
  EXCEL = "Excel",
  TEXT = "Text",
  URL = "URL",
  YOUTUBE_LINK = "YouTube Link",
  UNKNOWN = "Unknown",
}

export interface FAQ {
  question: string;
  answer: string;
}

export interface Document {
  id: string;
  name:string;
  type: DocumentType;
  tags: string[];
  contentSnippet: string; 
  fullContent?: string;
  uploadedAt: Date;
  isFavorite: boolean;
  sourceUrl?: string;
  generatedFaqs?: FAQ[];
}

export interface ChatMessage {
  id: string;
  sender: 'user' | 'ai';
  text: string;
  timestamp: Date;
  isLoading?: boolean;
  sources?: string[]; // For AI messages, to list relevant document names
}

export enum Theme {
  LIGHT = "light",
  DARK = "dark",
  SYSTEM = "system",
}

export enum Language {
  EN = "en",
  TA = "ta", // Tamil
  HI = "hi", // Hindi
  FR = "fr", // French
  DE = "de", // German
}

export const LANGUAGE_LABELS: Record<Language, string> = {
  [Language.EN]: "English",
  [Language.TA]: "தமிழ் (Tamil)",
  [Language.HI]: "हिन्दी (Hindi)",
  [Language.FR]: "Français (French)",
  [Language.DE]: "Deutsch (German)",
};


export enum ActiveView {
  HOME = "Home",
  DOCUMENTS = "Documents",
  AI_QUERY = "AI Query",
  MY_BOOKMARKS = "My Bookmarks",
  ANALYTICS = "Analytics",
  SETTINGS = "Settings",
}

export interface NavItem {
  name: ActiveView;
  icon: (props: React.SVGProps<SVGSVGElement>) => React.ReactNode;
  labelKey?: string; // For i18n
}

// Basic translation dictionary
export const UI_TRANSLATIONS: Record<Language, Record<string, string>> = {
  [Language.EN]: {
    home: "Home",
    documents: "Documents",
    ai_query: "AI Query",
    my_bookmarks: "My Bookmarks",
    analytics: "Analytics",
    settings: "Settings",
    add_document: "Add Document",
    document_hub_title: "Document Hub",
    search_documents_placeholder: "Search documents...",
    all_types: "All Types",
    all_tags: "All Tags",
    no_documents_found_home: "No documents found. Try adjusting your filters or adding new documents.",
    no_favorite_documents_found: "No favorite documents found.",

    homepage_welcome_title: "Welcome to Your Knowledge Management Hub",
    homepage_welcome_subtitle: "Unlock the power of your information. Store, search, and analyze with AI.",
    total_documents_stat: "Total Documents",
    your_favorites_stat: "Your Favorites",
    added_this_week_stat: "Added This Week",
    quick_action_add_doc_title: "Add New Document",
    quick_action_add_doc_desc: "Upload or link new information to your knowledge base.",
    quick_action_explore_docs_title: "Explore Documents",
    quick_action_explore_docs_desc: "Browse, filter, and manage all your stored documents.",
    quick_action_ask_ai_title: "Ask AI Assistant",
    quick_action_ask_ai_desc: "Get insights and answers from your documents using AI.",
    quick_action_analytics_title: "View Analytics",
    quick_action_analytics_desc: "Understand your knowledge base with insightful reports.",
    knowledge_quote: "\"Knowledge is power. Information is liberating. Education is the premise of progress, in every society, in every family.\" - Kofi Annan",
    get_started_title: "Get Started",
    homepage_how_to_use_title: "How to Use This App",
    step_label: "Step",
    how_to_step_1_title: "Add Your Information",
    how_to_step_1_desc: "Start by adding your documents, web links, or text notes. Click 'Add Document' to upload files or input text and URLs. Organize them with tags for easy retrieval.",
    how_to_step_2_title: "Explore & Manage",
    how_to_step_2_desc: "Navigate to the 'Documents' section to browse, search, and filter all your stored information. Mark important items as favorites for quick access via 'My Bookmarks'.",
    how_to_step_3_title: "Ask the AI Assistant",
    how_to_step_3_desc: "Use the 'AI Query' feature to ask questions about your documents. The AI can summarize content, answer specific queries, and help you find relevant information quickly. You can type or use voice input.",
    how_to_step_4_title: "Gain Insights",
    how_to_step_4_desc: "Visit 'Analytics' to see an overview of your knowledge base, including document types, popular tags, and recent activity. Understand how your information is structured.",
    how_to_step_5_title: "Customize Your Experience",
    how_to_step_5_desc: "Go to 'Settings' to personalize the app's appearance (theme), language, and manage your data preferences. Ensure the app works just the way you like it.",

    // Settings View
    settings_title: "System Settings",
    settings_description: "Customize your application experience and manage preferences.",
    appearance_settings_title: "Appearance",
    theme_label: "Theme",
    theme_light: "Light",
    theme_dark: "Dark",
    theme_system: "System",
    language_settings_title: "Language",
    language_label: "Application Language",
    ai_config_title: "AI Configuration",
    ai_service_status_label: "AI Service Status:",
    ai_service_available: "Available",
    ai_service_unavailable: "Unavailable (API Key not configured)",
    ai_model_label: "Current AI Model:",
    data_management_title: "Data Management",
    data_storage_info: "Your document data, theme, and language preferences are stored locally in your browser's localStorage. This data is private to this browser on this computer.",
    clear_local_data_button: "Clear All Local Data",
    clear_data_confirm_title: "Confirm Data Deletion",
    clear_data_confirm_message: "Are you sure you want to delete all local data? This action cannot be undone and will remove all your documents, settings, and preferences.",
    cancel_button: "Cancel",
    confirm_delete_button: "Yes, Delete Everything",
    about_section_title: "About",
    app_name_label: "Application Name:",
    app_version_label: "Version:",
    app_copyright_label: "Copyright:",
    app_powered_by_label: "Powered by:",
    settings_saved_toast: "Settings saved successfully!",
  },
  [Language.TA]: {
    home: "முகப்பு",
    documents: "ஆவணங்கள்",
    ai_query: "AI கேள்வி",
    my_bookmarks: "என் புக்மார்க்குகள்",
    analytics: "பகுப்பாய்வு",
    settings: "அமைப்புகள்",
    add_document: "ஆவணத்தைச் சேர்",
    document_hub_title: "ஆவண மையம்",
    search_documents_placeholder: "ஆவணங்களைத் தேடுங்கள்...",
    all_types: "அனைத்து வகைகள்",
    all_tags: "அனைத்து குறிச்சொற்கள்",
    no_documents_found_home: "எந்த ஆவணங்களும் இல்லை. உங்கள் வடிப்பான்களை சரிசெய்யவும் அல்லது புதிய ஆவணங்களைச் சேர்க்கவும்.",
    no_favorite_documents_found: "பிடித்தமான ஆவணங்கள் எதுவும் இல்லை.",

    homepage_welcome_title: "உங்கள் அறிவு மேலாண்மை மையத்திற்கு வரவேற்கிறோம்",
    homepage_welcome_subtitle: "உங்கள் தகவலின் சக்தியைத் திறக்கவும். AI மூலம் சேமிக்கவும், தேடவும் மற்றும் பகுப்பாய்வு செய்யவும்.",
    total_documents_stat: "மொத்த ஆவணங்கள்",
    your_favorites_stat: "உங்களுக்குப் பிடித்தவை",
    added_this_week_stat: "இவ்வாரம் சேர்க்கப்பட்டவை",
    quick_action_add_doc_title: "புதிய ஆவணத்தைச் சேர்",
    quick_action_add_doc_desc: "உங்கள் அறிவுத் தளத்தில் புதிய தகவலைப் பதிவேற்றவும் அல்லது இணைக்கவும்.",
    quick_action_explore_docs_title: "ஆவணங்களை ஆராயுங்கள்",
    quick_action_explore_docs_desc: "உங்கள் சேமிக்கப்பட்ட அனைத்து ஆவணங்களையும் உலாவவும், வடிகட்டவும் மற்றும் நிர்வகிக்கவும்.",
    quick_action_ask_ai_title: "AI உதவியாளரிடம் கேளுங்கள்",
    quick_action_ask_ai_desc: "AI ஐப் பயன்படுத்தி உங்கள் ஆவணங்களிலிருந்து நுண்ணறிவுகளையும் பதில்களையும் பெறுங்கள்.",
    quick_action_analytics_title: "பகுப்பாய்வைப் பார்க்கவும்",
    quick_action_analytics_desc: "நுண்ணறிவு அறிக்கைகளுடன் உங்கள் அறிவுத் தளத்தைப் புரிந்து கொள்ளுங்கள்.",
    knowledge_quote: "\"அறிவு சக்தி. தகவல் விடுதலை தருகிறது. கல்வி என்பது ஒவ்வொரு சமூகத்திலும், ஒவ்வொரு குடும்பத்திலும் முன்னேற்றத்தின் அடிப்படை.\" - கோஃபி அன்னான்",
    get_started_title: "தொடங்குங்கள்",
    homepage_how_to_use_title: "இந்த பயன்பாட்டை எவ்வாறு பயன்படுத்துவது",
    step_label: "படி",
    how_to_step_1_title: "உங்கள் தகவலைச் சேர்க்கவும்",
    how_to_step_1_desc: "உங்கள் ஆவணங்கள், இணைய இணைப்புகள் அல்லது உரை குறிப்புகளைச் சேர்ப்பதன் மூலம் தொடங்கவும். கோப்புகளைப் பதிவேற்ற அல்லது உரை மற்றும் URL களை உள்ளிட 'ஆவணத்தைச் சேர்' என்பதைக் கிளிக் செய்யவும். எளிதாக மீட்டெடுக்க குறிச்சொற்களுடன் அவற்றை ஒழுங்கமைக்கவும்.",
    how_to_step_2_title: "ஆராயுங்கள் & நிர்வகிக்கவும்",
    how_to_step_2_desc: "உங்கள் சேமிக்கப்பட்ட எல்லா தகவல்களையும் உலாவவும், தேடவும் மற்றும் வடிகட்டவும் 'ஆவணங்கள்' பகுதிக்குச் செல்லவும். 'என் புக்மார்க்குகள்' வழியாக விரைவான அணுகலுக்காக முக்கியமான உருப்படிகளை பிடித்தவையாகக் குறிக்கவும்.",
    how_to_step_3_title: "AI உதவியாளரிடம் கேளுங்கள்",
    how_to_step_3_desc: "உங்கள் ஆவணங்களைப் பற்றிய கேள்விகளைக் கேட்க 'AI கேள்வி' அம்சத்தைப் பயன்படுத்தவும். AI உள்ளடக்கத்தைச் சுருக்கலாம், குறிப்பிட்ட கேள்விகளுக்கு பதிலளிக்கலாம் மற்றும் தொடர்புடைய தகவலை விரைவாகக் கண்டறிய உங்களுக்கு உதவலாம். நீங்கள் தட்டச்சு செய்யலாம் அல்லது குரல் உள்ளீட்டைப் பயன்படுத்தலாம்.",
    how_to_step_4_title: "நுண்ணறிவுகளைப் பெறுங்கள்",
    how_to_step_4_desc: "ஆவண வகைகள், பிரபலமான குறிச்சொற்கள் மற்றும் சமீபத்திய செயல்பாடு உள்ளிட்ட உங்கள் அறிவுத் தளத்தின் மேலோட்டத்தைக் காண 'பகுப்பாய்வு' ஐப் பார்வையிடவும். உங்கள் தகவல் எவ்வாறு கட்டமைக்கப்பட்டுள்ளது என்பதைப் புரிந்து கொள்ளுங்கள்.",
    how_to_step_5_title: "உங்கள் அனுபவத்தைத் தனிப்பயனாக்குங்கள்",
    how_to_step_5_desc: "பயன்பாட்டின் தோற்றம் (தீம்), மொழி ஆகியவற்றைத் தனிப்பயனாக்க மற்றும் உங்கள் தரவு விருப்பங்களை நிர்வகிக்க 'அமைப்புகள்' க்குச் செல்லவும். பயன்பாடு நீங்கள் விரும்பும் வழியில் செயல்படுவதை உறுதிப்படுத்தவும்.",
    
    settings_title: "கணினி அமைப்புகள்",
    settings_description: "உங்கள் பயன்பாட்டு அனுபவத்தைத் தனிப்பயனாக்கி விருப்பங்களை நிர்வகிக்கவும்.",
    appearance_settings_title: "தோற்றம்",
    theme_label: "தீம்",
    theme_light: "ஒளி",
    theme_dark: "இருள்",
    theme_system: "கணினி",
    language_settings_title: "மொழி",
    language_label: "பயன்பாட்டு மொழி",
    ai_config_title: "AI கட்டமைப்பு",
    ai_service_status_label: "AI சேவை நிலை:",
    ai_service_available: "கிடைக்கிறது",
    ai_service_unavailable: "கிடைக்கவில்லை (API விசை கட்டமைக்கப்படவில்லை)",
    ai_model_label: "தற்போதைய AI மாதிரி:",
    data_management_title: "தரவு மேலாண்மை",
    data_storage_info: "உங்கள் ஆவணத் தரவு, தீம் மற்றும் மொழி விருப்பத்தேர்வுகள் உங்கள் உலாவியின் localStorage இல் உள்நாட்டில் சேமிக்கப்படும். இந்தத் தரவு இந்தக் கணினியில் இந்த உலாவிக்கு தனிப்பட்டது.",
    clear_local_data_button: "அனைத்து உள்ளூர் தரவையும் அழிக்கவும்",
    clear_data_confirm_title: "தரவு அழிப்பை உறுதிப்படுத்தவும்",
    clear_data_confirm_message: "அனைத்து உள்ளூர் தரவையும் நீக்க விரும்புகிறீர்களா? இந்தச் செயலைச் செயல்தவிர்க்க முடியாது, மேலும் இது உங்கள் எல்லா ஆவணங்களையும், அமைப்புகளையும், விருப்பங்களையும் அகற்றும்.",
    cancel_button: "ரத்துசெய்",
    confirm_delete_button: "ஆம், அனைத்தையும் நீக்கு",
    about_section_title: "பற்றி",
    app_name_label: "பயன்பாட்டின் பெயர்:",
    app_version_label: "பதிப்பு:",
    app_copyright_label: "பதிப்புரிமை:",
    app_powered_by_label: "மூலம் இயக்கப்படுகிறது:",
    settings_saved_toast: "அமைப்புகள் வெற்றிகரமாக சேமிக்கப்பட்டன!",
  },
  [Language.HI]: {
    home: "होम",
    documents: "दस्तावेज़",
    ai_query: "एआई प्रश्न",
    my_bookmarks: "मेरे बुकमार्क",
    analytics: "विश्लेषिकी",
    settings: "सेटिंग्स",
    add_document: "दस्तावेज़ जोड़ें",
    document_hub_title: "दस्तावेज़ केंद्र",
    search_documents_placeholder: "दस्तावेज़ खोजें...",
    all_types: "सभी प्रकार",
    all_tags: "सभी टैग",
    no_documents_found_home: "कोई दस्तावेज़ नहीं मिला। अपने फ़िल्टर समायोजित करने का प्रयास करें या नए दस्तावेज़ जोड़ें।",
    no_favorite_documents_found: "कोई पसंदीदा दस्तावेज़ नहीं मिला।",
    
    homepage_welcome_title: "आपके ज्ञान प्रबंधन केंद्र में आपका स्वागत है",
    homepage_welcome_subtitle: "अपनी जानकारी की शक्ति को अनलॉक करें। AI के साथ स्टोर करें, खोजें और विश्लेषण करें।",
    total_documents_stat: "कुल दस्तावेज़",
    your_favorites_stat: "आपके पसंदीदा",
    added_this_week_stat: "इस सप्ताह जोड़े गए",
    quick_action_add_doc_title: "नया दस्तावेज़ जोड़ें",
    quick_action_add_doc_desc: "अपने ज्ञान आधार पर नई जानकारी अपलोड करें या लिंक करें।",
    quick_action_explore_docs_title: "दस्तावेज़ों का अन्वेषण करें",
    quick_action_explore_docs_desc: "अपने सभी संग्रहीत दस्तावेज़ों को ब्राउज़ करें, फ़िल्टर करें और प्रबंधित करें।",
    quick_action_ask_ai_title: "एआई सहायक से पूछें",
    quick_action_ask_ai_desc: "एआई का उपयोग करके अपने दस्तावेज़ों से अंतर्दृष्टि और उत्तर प्राप्त करें।",
    quick_action_analytics_title: "विश्लेषिकी देखें",
    quick_action_analytics_desc: "अंतर्दृष्टिपूर्ण रिपोर्ट के साथ अपने ज्ञान आधार को समझें।",
    knowledge_quote: "\"ज्ञान शक्ति है। सूचना मुक्तिदायक है। शिक्षा हर समाज में, हर परिवार में प्रगति का आधार है।\" - कोफी अन्नान",
    get_started_title: "शुरू हो जाओ",
    homepage_how_to_use_title: "इस ऐप का उपयोग कैसे करें",
    step_label: "चरण",
    how_to_step_1_title: "अपनी जानकारी जोड़ें",
    how_to_step_1_desc: "अपने दस्तावेज़, वेब लिंक, या टेक्स्ट नोट्स जोड़कर प्रारंभ करें। फ़ाइलें अपलोड करने या टेक्स्ट और URL इनपुट करने के लिए 'दस्तावेज़ जोड़ें' पर क्लिक करें। आसान पुनर्प्राप्ति के लिए उन्हें टैग के साथ व्यवस्थित करें।",
    how_to_step_2_title: "अन्वेषण करें और प्रबंधित करें",
    how_to_step_2_desc: "अपनी सभी संग्रहीत जानकारी को ब्राउज़ करने, खोजने और फ़िल्टर करने के लिए 'दस्तावेज़' अनुभाग पर जाएँ। 'मेरे बुकमार्क' के माध्यम से त्वरित पहुँच के लिए महत्वपूर्ण वस्तुओं को पसंदीदा के रूप में चिह्नित करें।",
    how_to_step_3_title: "एआई सहायक से पूछें",
    how_to_step_3_desc: "अपने दस्तावेज़ों के बारे में प्रश्न पूछने के लिए 'एआई प्रश्न' सुविधा का उपयोग करें। एआई सामग्री को सारांशित कर सकता है, विशिष्ट प्रश्नों का उत्तर दे सकता है, और आपको प्रासंगिक जानकारी शीघ्रता से खोजने में मदद कर सकता है। आप टाइप कर सकते हैं या ध्वनि इनपुट का उपयोग कर सकते हैं।",
    how_to_step_4_title: "अंतर्दृष्टि प्राप्त करें",
    how_to_step_4_desc: "दस्तावेज़ प्रकार, लोकप्रिय टैग और हाल की गतिविधि सहित अपने ज्ञान आधार का अवलोकन देखने के लिए 'विश्लेषिकी' पर जाएँ। समझें कि आपकी जानकारी कैसे संरचित है।",
    how_to_step_5_title: "अपने अनुभव को अनुकूलित करें",
    how_to_step_5_desc: "ऐप की उपस्थिति (थीम), भाषा को वैयक्तिकृत करने और अपनी डेटा प्राथमिकताओं को प्रबंधित करने के लिए 'सेटिंग्स' पर जाएँ। सुनिश्चित करें कि ऐप ठीक उसी तरह काम करता है जैसा आप चाहते हैं।",

    settings_title: "सिस्टम सेटिंग्स",
    settings_description: "अपने एप्लिकेशन अनुभव को अनुकूलित करें और वरीयताएँ प्रबंधित करें।",
    appearance_settings_title: "दिखावट",
    theme_label: "थीम",
    theme_light: "हल्का",
    theme_dark: "गहरा",
    theme_system: "सिस्टम",
    language_settings_title: "भाषा",
    language_label: "एप्लिकेशन भाषा",
    ai_config_title: "एआई कॉन्फ़िगरेशन",
    ai_service_status_label: "एआई सेवा स्थिति:",
    ai_service_available: "उपलब्ध",
    ai_service_unavailable: "अनुपलब्ध (एपीआई कुंजी कॉन्फ़िगर नहीं है)",
    ai_model_label: "वर्तमान एआई मॉडल:",
    data_management_title: "डेटा प्रबंधन",
    data_storage_info: "आपके दस्तावेज़ डेटा, थीम और भाषा प्राथमिकताएँ आपके ब्राउज़र के localStorage में स्थानीय रूप से संग्रहीत हैं। यह डेटा इस कंप्यूटर पर इस ब्राउज़र के लिए निजी है।",
    clear_local_data_button: "सभी स्थानीय डेटा साफ़ करें",
    clear_data_confirm_title: "डेटा हटाने की पुष्टि करें",
    clear_data_confirm_message: "क्या आप वाकई सभी स्थानीय डेटा हटाना चाहते हैं? यह कार्रवाई पूर्ववत नहीं की जा सकती है और आपके सभी दस्तावेज़ों, सेटिंग्स और प्राथमिकताओं को हटा देगी।",
    cancel_button: "रद्द करें",
    confirm_delete_button: "हाँ, सब कुछ हटाएँ",
    about_section_title: "बारे में",
    app_name_label: "एप्लिकेशन का नाम:",
    app_version_label: "संस्करण:",
    app_copyright_label: "कॉपीराइट:",
    app_powered_by_label: "द्वारा संचालित:",
    settings_saved_toast: "सेटिंग्स सफलतापूर्वक सहेजी गईं!",
  },
  [Language.FR]: {
    home: "Accueil",
    documents: "Documents",
    ai_query: "Requête IA",
    my_bookmarks: "Mes Favoris",
    analytics: "Analytique",
    settings: "Paramètres",
    add_document: "Ajouter un document",
    document_hub_title: "Hub de Documents",
    search_documents_placeholder: "Rechercher des documents...",
    all_types: "Tous les types",
    all_tags: "Tous les tags",
    no_documents_found_home: "Aucun document trouvé. Essayez d'ajuster vos filtres ou d'ajouter de nouveaux documents.",
    no_favorite_documents_found: "Aucun document favori trouvé.",
    homepage_welcome_title: "Bienvenue dans Votre Hub de Gestion des Connaissances",
    homepage_welcome_subtitle: "Libérez la puissance de vos informations. Stockez, recherchez et analysez avec l'IA.",
    total_documents_stat: "Documents Totaux",
    your_favorites_stat: "Vos Favoris",
    added_this_week_stat: "Ajoutés cette semaine",
    quick_action_add_doc_title: "Ajouter un Nouveau Document",
    quick_action_add_doc_desc: "Téléchargez ou liez de nouvelles informations à votre base de connaissances.",
    quick_action_explore_docs_title: "Explorer les Documents",
    quick_action_explore_docs_desc: "Parcourez, filtrez et gérez tous vos documents stockés.",
    quick_action_ask_ai_title: "Demander à l'Assistant IA",
    quick_action_ask_ai_desc: "Obtenez des informations et des réponses de vos documents grâce à l'IA.",
    quick_action_analytics_title: "Voir l'Analytique",
    quick_action_analytics_desc: "Comprenez votre base de connaissances grâce à des rapports perspicaces.",
    knowledge_quote: "\"Le savoir, c'est le pouvoir. L'information est libératrice. L'éducation est la base du progrès, dans chaque société, dans chaque famille.\" - Kofi Annan",
    get_started_title: "Commencer",
    homepage_how_to_use_title: "Comment utiliser cette application",
    step_label: "Étape",
    how_to_step_1_title: "Ajoutez vos informations",
    how_to_step_1_desc: "Commencez par ajouter vos documents, liens Web ou notes textuelles. Cliquez sur 'Ajouter un document' pour télécharger des fichiers ou saisir du texte et des URL. Organisez-les avec des balises pour une récupération facile.",
    how_to_step_2_title: "Explorer et gérer",
    how_to_step_2_desc: "Accédez à la section 'Documents' pour parcourir, rechercher et filtrer toutes vos informations stockées. Marquez les éléments importants comme favoris pour un accès rapide via 'Mes favoris'.",
    how_to_step_3_title: "Demandez à l'assistant IA",
    how_to_step_3_desc: "Utilisez la fonction 'Requête IA' pour poser des questions sur vos documents. L'IA peut résumer le contenu, répondre à des questions spécifiques et vous aider à trouver rapidement des informations pertinentes. Vous pouvez taper ou utiliser la saisie vocale.",
    how_to_step_4_title: "Obtenir des informations",
    how_to_step_4_desc: "Visitez 'Analytique' pour voir un aperçu de votre base de connaissances, y compris les types de documents, les balises populaires et l'activité récente. Comprenez comment vos informations sont structurées.",
    how_to_step_5_title: "Personnalisez votre expérience",
    how_to_step_5_desc: "Allez dans 'Paramètres' pour personnaliser l'apparence de l'application (thème), la langue et gérer vos préférences de données. Assurez-vous que l'application fonctionne comme vous le souhaitez.",

    settings_title: "Paramètres Système",
    settings_description: "Personnalisez votre expérience applicative et gérez vos préférences.",
    appearance_settings_title: "Apparence",
    theme_label: "Thème",
    theme_light: "Clair",
    theme_dark: "Sombre",
    theme_system: "Système",
    language_settings_title: "Langue",
    language_label: "Langue de l'application",
    ai_config_title: "Configuration IA",
    ai_service_status_label: "État du Service IA :",
    ai_service_available: "Disponible",
    ai_service_unavailable: "Indisponible (Clé API non configurée)",
    ai_model_label: "Modèle IA Actuel :",
    data_management_title: "Gestion des Données",
    data_storage_info: "Vos données de documents, votre thème et vos préférences linguistiques sont stockés localement dans le localStorage de votre navigateur. Ces données sont privées à ce navigateur sur cet ordinateur.",
    clear_local_data_button: "Effacer Toutes les Données Locales",
    clear_data_confirm_title: "Confirmer la Suppression des Données",
    clear_data_confirm_message: "Êtes-vous sûr de vouloir supprimer toutes les données locales ? Cette action est irréversible et supprimera tous vos documents, paramètres et préférences.",
    cancel_button: "Annuler",
    confirm_delete_button: "Oui, Tout Supprimer",
    about_section_title: "À Propos",
    app_name_label: "Nom de l'Application :",
    app_version_label: "Version :",
    app_copyright_label: "Copyright :",
    app_powered_by_label: "Propulsé par :",
    settings_saved_toast: "Paramètres enregistrés avec succès !",
  },
  [Language.DE]: {
    home: "Startseite",
    documents: "Dokumente",
    ai_query: "KI-Anfrage",
    my_bookmarks: "Meine Lesezeichen",
    analytics: "Analysen",
    settings: "Einstellungen",
    add_document: "Dokument hinzufügen",
    document_hub_title: "Dokumenten-Hub",
    search_documents_placeholder: "Dokumente suchen...",
    all_types: "Alle Typen",
    all_tags: "Alle Tags",
    no_documents_found_home: "Keine Dokumente gefunden. Passen Sie Ihre Filter an oder fügen Sie neue Dokumente hinzu.",
    no_favorite_documents_found: "Keine bevorzugten Dokumente gefunden.",
    homepage_welcome_title: "Willkommen in Ihrem Wissensmanagement-Hub",
    homepage_welcome_subtitle: "Entfesseln Sie die Kraft Ihrer Informationen. Speichern, suchen und analysieren Sie mit KI.",
    total_documents_stat: "Gesamtdokumente",
    your_favorites_stat: "Ihre Favoriten",
    added_this_week_stat: "Diese Woche hinzugefügt",
    quick_action_add_doc_title: "Neues Dokument hinzufügen",
    quick_action_add_doc_desc: "Laden Sie neue Informationen hoch oder verknüpfen Sie sie mit Ihrer Wissensdatenbank.",
    quick_action_explore_docs_title: "Dokumente erkunden",
    quick_action_explore_docs_desc: "Durchsuchen, filtern und verwalten Sie alle Ihre gespeicherten Dokumente.",
    quick_action_ask_ai_title: "KI-Assistent fragen",
    quick_action_ask_ai_desc: "Erhalten Sie Einblicke und Antworten aus Ihren Dokumenten mithilfe von KI.",
    quick_action_analytics_title: "Analysen anzeigen",
    quick_action_analytics_desc: "Verstehen Sie Ihre Wissensdatenbank mit aufschlussreichen Berichten.",
    knowledge_quote: "\"Wissen ist Macht. Information ist befreiend. Bildung ist die Grundlage des Fortschritts, in jeder Gesellschaft, in jeder Familie.\" - Kofi Annan",
    get_started_title: "Los geht's",
    homepage_how_to_use_title: "So verwenden Sie diese App",
    step_label: "Schritt",
    how_to_step_1_title: "Fügen Sie Ihre Informationen hinzu",
    how_to_step_1_desc: "Beginnen Sie mit dem Hinzufügen Ihrer Dokumente, Weblinks oder Textnotizen. Klicken Sie auf 'Dokument hinzufügen', um Dateien hochzuladen oder Text und URLs einzugeben. Organisieren Sie sie mit Tags für einen einfachen Abruf.",
    how_to_step_2_title: "Erkunden & Verwalten",
    how_to_step_2_desc: "Navigieren Sie zum Abschnitt 'Dokumente', um alle Ihre gespeicherten Informationen zu durchsuchen, zu suchen und zu filtern. Markieren Sie wichtige Elemente als Favoriten für den schnellen Zugriff über 'Meine Lesezeichen'.",
    how_to_step_3_title: "Fragen Sie den KI-Assistenten",
    how_to_step_3_desc: "Verwenden Sie die Funktion 'KI-Anfrage', um Fragen zu Ihren Dokumenten zu stellen. Die KI kann Inhalte zusammenfassen, spezifische Fragen beantworten und Ihnen helfen, relevante Informationen schnell zu finden. Sie können tippen oder Spracheingabe verwenden.",
    how_to_step_4_title: "Erkenntnisse gewinnen",
    how_to_step_4_desc: "Besuchen Sie 'Analysen', um einen Überblick über Ihre Wissensdatenbank zu erhalten, einschließlich Dokumenttypen, beliebter Tags und aktueller Aktivitäten. Verstehen Sie, wie Ihre Informationen strukturiert sind.",
    how_to_step_5_title: "Passen Sie Ihre Erfahrung an",
    how_to_step_5_desc: "Gehen Sie zu 'Einstellungen', um das Erscheinungsbild der App (Theme), die Sprache zu personalisieren und Ihre Dateneinstellungen zu verwalten. Stellen Sie sicher, dass die App so funktioniert, wie Sie es möchten.",

    settings_title: "Systemeinstellungen",
    settings_description: "Passen Sie Ihr Anwendungserlebnis an und verwalten Sie Präferenzen.",
    appearance_settings_title: "Erscheinungsbild",
    theme_label: "Thema",
    theme_light: "Hell",
    theme_dark: "Dunkel",
    theme_system: "System",
    language_settings_title: "Sprache",
    language_label: "Anwendungssprache",
    ai_config_title: "KI-Konfiguration",
    ai_service_status_label: "KI-Dienststatus:",
    ai_service_available: "Verfügbar",
    ai_service_unavailable: "Nicht verfügbar (API-Schlüssel nicht konfiguriert)",
    ai_model_label: "Aktuelles KI-Modell:",
    data_management_title: "Datenverwaltung",
    data_storage_info: "Ihre Dokumentdaten, Design- und Spracheinstellungen werden lokal im localStorage Ihres Browsers gespeichert. Diese Daten sind privat für diesen Browser auf diesem Computer.",
    clear_local_data_button: "Alle lokalen Daten löschen",
    clear_data_confirm_title: "Datenlöschung bestätigen",
    clear_data_confirm_message: "Möchten Sie wirklich alle lokalen Daten löschen? Diese Aktion kann nicht rückgängig gemacht werden und entfernt alle Ihre Dokumente, Einstellungen und Präferenzen.",
    cancel_button: "Abbrechen",
    confirm_delete_button: "Ja, alles löschen",
    about_section_title: "Über",
    app_name_label: "Anwendungsname:",
    app_version_label: "Version:",
    app_copyright_label: "Copyright:",
    app_powered_by_label: "Unterstützt von:",
    settings_saved_toast: "Einstellungen erfolgreich gespeichert!",
  }
};