name: Build and Deploy to FTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Inject .env with Google API Key
      run: echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env

    - name: Build App
      run: npm run build

    - name: Upload to FTP
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        
        # Connecting to your server. Based on your screenshot, port 3000 is correct for you.
        lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -p 3000 ${{ secrets.FTP_HOST }} <<EOF
        set ftp:ssl-allow no

        # FIX: Using the full, correct path as shown in your FileZilla screenshot.
        # This creates the final app directory if it doesn't exist.
        mkdir -p /apps.hereandnowai.com/apps/${{ github.event.repository.name }}
        
        # Mirror the contents of the local 'dist' folder to the correct remote directory.
        mirror -R --delete --verbose ./dist /apps.hereandnowai.com/apps/${{ github.event.repository.name }}
        
        bye
        EOF