name: Build, Test, Deploy via FTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Inject .env with Google API Key
      run: echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env

    - name: Build App
      run: npm run build

    - name: Upload to FTP (port 3000) using lftp
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        lftp -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -p 3000 ${{ secrets.FTP_HOST }} <<EOF
        set ftp:ssl-allow no
        mirror -R ./dist /hereandnowai/knowledge_management --verbose
        bye
