name: Build and Deploy to FTP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm install

    - name: Inject .env with Google API Key
      run: echo "GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}" > .env

    - name: Build App
      run: npm run build

    - name: Upload to FTP
      run: |
        sudo apt-get update && sudo apt-get install -y lftp
        
        # FIX: Added the '-d' flag for a full debug log
        # This will show the exact reason for the connection failure
        lftp -d -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} -p 3000 ${{ secrets.FTP_HOST }} <<EOF
        set ftp:ssl-allow no
        
        # Test command to see if we are connected before mirroring
        ls

        # Create the remote directory if it doesn't exist
        mkdir -p /apps.hereandnowai.com/apps/${{ github.event.repository.name }}
        
        # Mirror the contents of the local 'dist' folder to the correct remote directory
        mirror -R --delete --verbose ./dist /apps.hereandnowai.com/apps/${{ github.event.repository.name }}
        
        bye
        EOF